# Generated by Django 2.2 on 2019-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0003_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(default='ig.png', upload_to='profile/'),
        ),
    ]
