# Generated by Django 2.2 on 2019-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0005_notifactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifactions',
            new_name='Notifications',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='status',
            new_name='message',
        ),
    ]
