# Generated by Django 2.2 on 2019-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0006_auto_20190814_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
